# User-agent used for querying Wikidata API
CUSTOM_UA: "spd (cloud-vps) -- isaac@wikimedia.org"

DEBUG: False

ENABLE_UI: False

EARLIEST_TS: '2020-01-01T00:00:00Z'
MOST_RECENT_REV_TS: '2020-09-30T23:59:59Z'
JSON_SORT_KEYS: False
TEMPORAL_OFFSET: '(-1, 0, 1)'
NAMESPACES: [0, 1, 118]
EDIT_WINDOW: 5

BASIC_AUTH_USERNAME: 'research'
BASIC_AUTH_PASSWORD: 'spd'

LISTEN_IP: 0.0.0.0
